# Generated by Django 5.1.6 on 2025-03-01 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('q_type', models.CharField(choices=[('scq', 'Szimpla válasz'), ('mcq', 'Többszörös válasz'), ('true_false', 'Igaz/Hamis'), ('short_answer', 'Rövid válasz'), ('numerical', 'Számmal megadott válasz')], max_length=255)),
                ('difficulty', models.IntegerField()),
                ('category', models.CharField(choices=[('science', 'Tudomány'), ('history', 'Történelem'), ('geography', 'Földrajz'), ('math', 'Matematika'), ('literature', 'Irodalom'), ('art', 'Művészet'), ('music', 'Zene'), ('sports', 'Sport'), ('technology', 'Technológia'), ('health', 'Egészség'), ('languages', 'Nyelvek'), ('movies', 'Filmek'), ('gaming', 'Videójátékok'), ('politics', 'Politika'), ('economy', 'Gazdaság'), ('environment', 'Környezetvédelem'), ('psychology', 'Pszichológia'), ('philosophy', 'Filozófia'), ('mythology', 'Mitológia'), ('space', 'Űrkutatás')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.question')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.gameuser')),
            ],
        ),
    ]
