# Generated by Django 5.1.6 on 2025-03-01 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
    ]
